services:
  forward-ajm1-bot:
    build: .
    environment:
      ADMINS: 567835245
      API_ID: 7628928
      API_HASH: 90a82f85b152b1928f1e81c1cd4a7635
      BOT_TOKEN: $BOT_TOKEN
      COLLECTION_NAME: kcforv2
      LOG_CHANNEL: -1001708025066
      DATABASE_NAME: Cluster0
      DATABASE_URI: mongodb+srv://kcajm:kcajm@cluster0.8erks.mongodb.net/?retryWrites=true&w=majority
      TARGET_CHANNEL: -1001786328139
      BOT_USERNAME: $BOT_USERNAME
    resources:
      cpu: 1000m
      memory: 3Gi
